Dockerfile: install ca-certificates
When building the docker image, sometimes the download of artifacts fails because of certificate issues. E.g.:
```
Resolving golang.org (golang.org)... 172.217.168.49, 2a00:1450:400a:802::2011
Connecting to golang.org (golang.org)|172.217.168.49|:443... connected.
ERROR: The certificate of 'golang.org' is not trusted.
ERROR: The certificate of 'golang.org' doesn't have a known issuer.
```