stringutil: fix length issues
Incorrect use of the API of stringutil can cause the package to cause a panic.

```
--- FAIL: TestFieldsNZeroLengthSlice (0.00s)
panic: runtime error: index out of range [-1] [recovered, repanicked]

goroutine 20 [running]:
testing.tRunner.func1.2({0x651900, 0xb66b7520480})
	/usr/local/go/src/testing/testing.go:1974 +0x232
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1977 +0x349
panic({0x651900?, 0xb66b7520480?})
	/usr/local/go/src/runtime/panic.go:860 +0x13a
go.opentelemetry.io/ebpf-profiler/stringutil.FieldsN({0x66c194?, 0x82f4c0?}, {0xb66b7595760?, 0x0?, 0x0?})
	/home/flehner/go/src/github.com/open-telemetry/opentelemetry-ebpf-profiler/stringutil/stringutil.go:48 +0x167
go.opentelemetry.io/ebpf-profiler/stringutil.TestFieldsNZeroLengthSlice(0xb66b76b6008)
	/home/flehner/go/src/github.com/open-telemetry/opentelemetry-ebpf-profiler/stringutil/stringutil_test.go:40 +0x32
testing.tRunner(0xb66b76b6008, 0x680d28)
	/usr/local/go/src/testing/testing.go:2036 +0xea
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:2101 +0x4c5
FAIL	go.opentelemetry.io/ebpf-profiler/stringutil	0.035s
FAIL
```

Prevent this issue by checking values.

Signed-off-by: Florian Lehner <florian.lehner@elastic.co>